- name: "install prerequisite"
  import_playbook: playbooks/pre.yml
- name: "install apache"
  import_playbook: playbooks/apache.yml
- import_playbook: playbooks/mysql.yml
- import_playbook: playbooks/php.yml
- import_playbook: playbooks/composer.yml
- import_playbook: playbooks/project.yml
