- hosts: ec2_ip
  tasks:
  - name: "update package"
    apt:
       upgrade: yes
       update_cache: yes
  - name: "Install apache httpd"
    apt:
     name: "apache2"
     state: present
  - name: "Start the service"
    service:
       name: "apache2"
       state: started
       enabled: yes
