- hosts: ec2_ip
  tasks:
  - name: "curl softwares"
    shell:
       cmd: curl -sS https://getcomposer.org/installer | php
  - name: "mv composer "
    command: sudo mv composer.phar /usr/local/bin/composer
  - name: "make executable"
    command: chmod +x /usr/local/bin/composer

